session_name: default
windows:
  - window_name: juno
    start_directory: ~/j
    panes:
      - null
  - window_name: email
    panes:
      - null
  - window_name: tjjk
    start_directory: ~/t
    panes:
      - null
  - window_name: blog
    start_directory: ~/i/blog
    panes:
      - null
      - miniserve build -p 8964&; while inotifywait -q -e modify -r src/; make LIVE=y; end
  - window_name: slide
    start_directory: ~/t/meet
    panes:
      - null
      - while inotifywait -q -e modify -r src/; make ; end
