session_name: default
windows:
  - window_name: tjjk
    start_directory: ~/t
    panes:
      - null
  - window_name: email
    panes:
      - null
  - window_name: blog
    start_directory: ~/i/blog
    panes:
      - null
