session_name: default
windows:
  - window_name: work
    start_directory: ~/Documents
    panes:
      - ip a
  - window_name: email
    layout: main-horizontal
    panes:
      - neomutt
      - newsboat
  - window_name: blog
    start_directory: ~/Documents/blog
    layout: main-horizontal
    panes:
      - null
      - null
  - window_name: ledger
    panes:
      - null
  - window_name: music
    panes:
      - musicfox
