session_name: default
start_directory: ~/Documents
windows:
  - window_name: work
    panes:
      - ip a
  - window_name: email
    layout: main-horizontal
    panes:
      - neomutt
      - newsboat
