session_name: default
windows:
  - window_name: work
    start_directory: ~/t
    panes:
      - ip a
  - window_name: email
    layout: main-vertical
    panes:
      - neomutt
      - null
  - window_name: blog
    start_directory: ~/i/blog
    layout: main-horizontal
    panes:
      - null
      - null
